### ISSUE TITLE
Possibility for non-socat use for gpg agent via Remote Forward

### ISSUE THREAD

**Issue by dschaper** [Lexicality/wsl-relay#1]
Thanks for a great tool!

I'm currently using it via WSL to remote forward `gpg-agent` via WSL `ssh`. This allows for `gpg` use on other instances remotely. [1] Currently I'm bound by needing WSL as `socat` doesn't seem to be in Windows-land. 

Is there a possibility to have either something that can read/write to stdin/stdout of `wsl-relay` in Windows land, or to have a tcp port be the entry/exit? 

[1] https://wiki.gnupg.org/AgentForwarding

**Comment by Lexicality** [comment]
Sorry, I'm not entirely sure I understand.
This tool works by launching a windows process (wsl-relay.exe) inside WSL so that linux applications can access Windows only pipes (eg gpg-agent).
If you want to connect to your Windows GPG agent in windows, the file `%APPDATA%\gnupg\S.gpg-agent` contains the TCP port & nonce required to make a direct connection.

**Comment by dschaper** [comment]
Thanks for the reply. 

The goal is to have Windows GPG agent available remotely to linux hosts without needing WSL in the process. This is admittedly a side case but a similar tool https://github.com/benpye/wsl-ssh-pageant has both WSL and Windows modes. 

The first situation is forwarding Windows `S.gpg-agent` to a linux host via `ssh`. The command is ` ssh -R /run/user/1000/gnupg/S.gpg-agent:C\:/<path>/S.gpg-agent dschaper@10.0.0.2`, using Windows OpenSSH binary. This causes the linux host to fail when `gpg` commands are run with:

```sh
getsockopt SO_ERROR failed
connect_to C:/<path>/S.gpg-agent port -2: failed.
gpg: can't connect to the agent: End of file
```

Second situation is using `wsl-relay` via `socat UNIX-LISTEN:/c/socket/S.gpg-agent,fork, EXEC:'wsl-relay.exe --input-closes --pipe-closes --gpg -v',nofork` and then `ssh -R /run/user/1000/gnupg/S.gpg-agent:C\:/socket/S.gpg-agent dschaper@10.0.0.2` using Windows OpenSSH. Failure mode is the same, `getsockopt SO_ERROR failed` and no logging of any activity in `wsl-relay`. 

What does work is to run `socat UNIX-LISTEN:/home/dschaper/S.gpg-agent,fork, EXEC:'/e/bin/wsl-relay.exe --input-closes --pipe-closes --gpg -v',nofork`. Then ` ssh -R /run/user/1000/gnupg/S.gpg-agent:/home/dschaper/S.gpg-agent dschaper@10.0.0.2` via WSL `ssh`. Success as shown:

```sh
2019/11/13 07:05:51 Opening an Assuan connection via C:\Users\dan\AppData\Roaming\gnupg\S.gpg-agent
2019/11/13 07:05:51 Port: 53356, Nonce: B7A1A7A2FD269BE85243D898E74CDBE2
2019/11/13 07:05:51 connected
2019/11/13 07:05:51 copy from stdin to pipe finished
```

**Comment by Lexicality** [comment]
Right, so if I understand you correctly you want a program that uses the code in `assuan.go` to convert the Windows TCP gpg-agent into a Windows named pipe compatible with the Linux gpg-agent that you then use the openssh binary on cmd.exe to forward to a server?

Assuming `ssh.exe` is capable of forwarding named pipes, that shouldn't be too difficult but is kind of out of scope for this project. I'll have a poke tonight though.

**Comment by dschaper** [comment]
I think so, I'll talk over with some others that are interested and see if they concur. 

I know this is off the far side of the project but if we can get something up then I would be very happy to pick up coffee/beer or whatever.

**Comment by Lexicality** [comment]
I've bodged something together on the [wip-pipe-transfer](/Lexicality/wsl-relay/tree/wip-pipe-transfer) branch, can you have a go please?
I don't have anything set up I can test this with right now and I'm pretty hazy about how Windows pipes work, so I don't know if it will actually do what you want, but it should be a good starting point

**Comment by dschaper** [comment]
Thanks! I've compiled the branch and it is spinning up but crashes out. 
PS:
```powershell

PS C:\Users\dan> cat .\.ssh\config
Host hyperdeb
  HostName hyperdeb
  User dschaper
  RemoteForward /run/user/1000/gnupg/S.gpg-agent //./pipe/wsl-pipe

PS C:\Users\dan> C:\bin\wsl-relay.exe -v --input-closes --pipe-closes --gpg="S.gpg-agent.extra" --target-pipe 'wsl-pipe'
2019/11/18 15:44:23 Opening an Assuan connection via C:\Users\dan\AppData\Roaming\gnupg\S.gpg-agent.extra
2019/11/18 15:44:23 Port: 53889, Nonce: F681E5C5537303191BE5B0FD2123646B
2019/11/18 15:44:23 connected
2019/11/18 15:44:23 copy from stdin to pipe finished
```

Debian remote:
```bash
PS C:\Users\dan> ssh hyperdeb
Linux HyperDeb 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Fri Nov 15 15:53:45 2019 from 10.0.0.1
dschaper@HyperDeb:~$ gpg -K
getsockopt SO_ERROR failed
connect_to //./pipe/wsl-pipe port -2: failed.
gpg: can't connect to the agent: End of file
gpg: no gpg-agent running in this session
```

I think it's from the socket not supporting that `SO_ERROR` option but I'm pretty sketchy on Windows internals as well.

**Comment by Lexicality** [comment]
Apologies for the extreme delay on this one but it looks like winssh doesn't actually support named pipes: https://github.com/PowerShell/Win32-OpenSSH/issues/435
If this ever gets resolved I'll give it another go however
